CREATE OR REPLACE WAREHOUSE SALES_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

CREATE OR REPLACE DATABASE CUSTOMER_SALES_DB;

CREATE OR REPLACE SCHEMA SALES_SCHEMA;

USE WAREHOUSE SALES_WH;

USE DATABASE CUSTOMER_SALES_DB;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;



CREATE STAGE IF NOT EXISTS SALES_STAGE FILE_FORMAT = CSV_FILE_FORMAT;



CREATE OR REPLACE TABLE CUSTOMERS
(
    CUSTOMER_ID INT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(100)
);

CREATE OR REPLACE TABLE FOODITEMS
(
    FOOD_ID INT,
    NAME VARCHAR(100),
    PRICE NUMBER(10,2),
    CATEGORY VARCHAR(50),
    AVAILABILITY VARCHAR(20)
);

CREATE OR REPLACE TABLE ORDERS
(
    ORDER_ID INT,
    CUSTOMER_ID INT,
    FOOD_ID INT,
    QUANTITY INT,
    ORDER_DATE TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL_AMOUNT NUMBER(10,2)
);

COPY INTO CUSTOMERS
FROM @SALES_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT);

COPY INTO FOODITEMS
FROM @SALES_STAGE/fooditems.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT);

COPY INTO ORDERS
FROM @SALES_STAGE/orders.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT);

list @sales_stage


select * from customers;


SELECT
    C.CUSTOMER_ID,
    CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME
ORDER BY TOTAL_SPENT DESC;

SELECT
    C.CUSTOMER_ID,
    CONCAT(C.FIRST_NAME,' ',
    C.LAST_NAME) AS Customer_Name,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 1;

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS;

SELECT
    F.CATEGORY,
    SUM(O.TOTAL_AMOUNT) AS REVENUE
FROM ORDERS O
JOIN FOODITEMS F
ON O.FOOD_ID = F.FOOD_ID
GROUP BY F.CATEGORY
ORDER BY REVENUE DESC;

SELECT
    STATUS AS ORDER_STATUS,
    SUM(TOTAL_AMOUNT) AS REVENUE
FROM ORDERS
GROUP BY STATUS
ORDER BY REVENUE DESC;

SELECT
    C.CUSTOMER_ID,
    CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 3;


SELECT
    C.CUSTOMER_ID,
    CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
    COUNT(O.ORDER_ID) AS ORDERS_PLACED
FROM ORDERS O
JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME
ORDER BY ORDERS_PLACED DESC;

SELECT *
FROM ORDERS
WHERE STATUS = 'Delivered';

SELECT
    O.ORDER_ID,
    CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
    O.ORDER_DATE,
    O.STATUS,
    O.TOTAL_AMOUNT
FROM ORDERS O
JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_DATE > '2026-07-12'
ORDER BY O.ORDER_DATE;

CREATE OR REPLACE VIEW CUSTOMER_SALES_REPORT AS
SELECT
    C.CUSTOMER_ID,
    CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME;

SELECT *
FROM CUSTOMER_SALES_REPORT;

SELECT *
FROM CUSTOMER_SALES_REPORT
ORDER BY TOTAL_SPENT DESC;