CREATE OR REPLACE WAREHOUSE ENTERPRISE_WH 
WITH
WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND=60
AUTO_RESUME= TRUE ;


USE WAREHOUSE ENTERPRISE_WH ;

CREATE OR REPLACE DATABASE ENTERPRISE_DB;
USE DATABASE ENTERPRISE_DB;
CREATE OR REPLACE SCHEMA SALES_SCHEMA;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
WITH 
TYPE = CSV 
FIELD_DELIMITER= ','
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'

CREATE OR REPLACE STAGE ENTERPRISE_STAGE;

CREATE OR REPLACE  TABLE CUSTOMERS(

CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(30),
CITY VARCHAR(30),
MEMBERSHIP VARCHAR(20)
);

CREATE OR REPLACE TABLE PRODUCTS(

PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(40),
CATEGORY VARCHAR(50),
PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE BRANCHES (
BRANCH_ID INT,
BRANCH_NAME VARCHAR(100),
STATE VARCHAR(30)
);


CREATE OR REPLACE TABLE SALES(
SALES_ID INT,
PRODUCT_ID INT,
CUSTOMER_ID INT,
BRANCH_ID INT,
QUANTITY INT ,
SALES_DATE DATE,
TOTAL_AMOUNT NUMBER(12,2)
);

LIST @ENTERPRISE_STAGE


COPY INTO SALES
FROM @ENTERPRISE_STAGE/sales_history.csv 
FILE_FORMAT= (FORMAT_NAME= CSV_FILE_FORMAT );

COPY INTO CUSTOMERS
FROM @ENTERPRISE_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT);


COPY INTO BRANCHES
FROM @ENTERPRISE_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT);

COPY INTO PRODUCTS
FROM @ENTERPRISE_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT);

-- SELECT * FROM SALES;

-- REMOVE @ENTERPRISE_STAGE/new_sales.txt;
-- REMOVE @ENTERPRISE_STAGE/sales_history.txt;

select count(*) from sales;

CREATE OR REPLACE STREAM SALES_STREAM ON TABLE SALES;

SHOW STREAMS;

COPY INTO SALES
FROM @ENTERPRISE_STAGE/new_sales.csv
FILE_FORMAT= (FORMAT_NAME = CSV_FILE_FORMAT );

SELECT * FROM SALES ORDER BY SALES_ID;

SELECT * FROM SALES_STREAM;


SELECT
    SALES_ID,
    COUNT(*) AS COUNT
FROM SALES
GROUP BY SALES_ID
HAVING COUNT(*) > 1;

SELECT DISTINCT
    S.CUSTOMER_ID
FROM SALES S
LEFT JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

-- SELECT
--     SALES_ID,
--     CUSTOMER_ID,
--     PRODUCT_ID
-- FROM SALES
-- ORDER BY SALES_ID;

SELECT DISTINCT
    S.PRODUCT_ID
FROM SALES S
LEFT JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

SELECT COUNT(*) AS NEW_RECORD_COUNT
FROM SALES_STREAM;

SELECT SALES_ID FROM SALES ORDER BY SALES_ID;

INSERT INTO SALES VALUES 
(10,5,102,3,1,'2026-07-10',25000)

DELETE FROM SALES WHERE SALES_ID=10

SELECT *
FROM SALES
AT (OFFSET => -300)
WHERE SALES_ID = 10;

INSERT INTO SALES
SELECT *
FROM SALES
AT (OFFSET => -300)
WHERE SALES_ID = 10;

SELECT SALES_ID FROM SALES ORDER BY SALES_ID;


-- PHASE 6
-- TASK 21
CREATE OR REPLACE TABLE SALES_TEST CLONE SALES;
-- TASK 22
SELECT * FROM SALES_TEST ORDER BY SALES_ID;
-- TASK 23
INSERT INTO SALES_TEST VALUES (11, 1, 101, 1, 1, '2026-07-11', 60000);
-- TASK 24
SELECT SALES_ID FROM SALES ORDER BY SALES_ID;


-- PHASE 7
-- TASK 25
CREATE OR REPLACE TASK DAILY_SALES_TASK
WAREHOUSE = ENTERPRISE_WH
SCHEDULE = 'USING CRON 0 0 * * * UTC'
AS
INSERT INTO SALES
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
FROM SALES_STREAM
WHERE METADATA$ACTION = 'INSERT';
-- TASK 26
ALTER TASK DAILY_SALES_TASK RESUME;

-- TASK 27
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'DAILY_SALES_TASK'
ORDER BY SCHEDULED_TIME DESC;

-- PHASE 8
-- TASK 28
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;


-- UPDATE SALES
-- SET
--     CUSTOMER_ID = PRODUCT_ID,
--     PRODUCT_ID = CUSTOMER_ID;

-- TASK 29
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

-- TASK 30
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

-- TASK 31
SELECT
    DATE_TRUNC('MONTH', SALE_DATE) AS MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES
GROUP BY DATE_TRUNC('MONTH', SALE_DATE)
ORDER BY MONTH;

-- TASK 32
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- TASK 33
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- TASK 34
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- TASK 35
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COUNT(S.SALES_ID) AS PURCHASE_COUNT
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY PURCHASE_COUNT DESC;

-- TASK 36
SELECT
    SALES_ID,
    SALES_DATE,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALES_DATE, SALES_ID
    ) AS RUNNING_REVENUE
FROM SALES
ORDER BY SALES_DATE, SALES_ID;

-- TASK 37
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

-- PHASE 9
-- TASK 38
CREATE OR REPLACE VIEW CUSTOMER_REVENUE AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME;

SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;


-- TASK 39
CREATE OR REPLACE VIEW BRANCH_REVENUE AS
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME;
    
SELECT *
FROM BRANCH_REVENUE
ORDER BY TOTAL_REVENUE DESC;