

-- TASK 1
-- CREATE DATABASE AND SCHEMA
 

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE RETAIL_DW;

USE DATABASE RETAIL_DW;

CREATE OR REPLACE SCHEMA SALES_ANALYTICS;

USE SCHEMA SALES_ANALYTICS;



-- SOURCE INGESTION
-- STAGE + FILE FORMAT + STAGING TABLES



-- CREATE STAGE


CREATE OR REPLACE STAGE RETAIL_STAGE;


-- CREATE FILE FORMAT


CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');


-- CHECK FILES


LIST @RETAIL_STAGE;



-- STAGING TABLE 1: STORES


CREATE OR REPLACE TABLE STG_STORES (
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);


-- STAGING TABLE 2: PRODUCTS

CREATE OR REPLACE TABLE STG_PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);



-- STAGING TABLE 3: INITIAL CUSTOMERS


CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);



-- STAGING TABLE 4: CUSTOMER UPDATES


CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);



-- LOAD CSV FILES INTO STAGING TABLES


COPY INTO STG_STORES
FROM @RETAIL_STAGE/stores.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';




COPY INTO STG_PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
VALIDATION_MODE = 'RETURN_ERRORS';

COPY INTO STG_CUSTOMERS_INITIAL
FROM @RETAIL_STAGE/customers_initial.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO STG_CUSTOMER_UPDATES
FROM @RETAIL_STAGE/customer_updates.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';



-- VALIDATE STAGING DATA


SELECT 'STG_STORES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT
FROM STG_STORES

UNION ALL

SELECT 'STG_PRODUCTS', COUNT(*)
FROM STG_PRODUCTS

UNION ALL

SELECT 'STG_CUSTOMERS_INITIAL', COUNT(*)
FROM STG_CUSTOMERS_INITIAL

UNION ALL

SELECT 'STG_CUSTOMER_UPDATES', COUNT(*)
FROM STG_CUSTOMER_UPDATES;





-- TASK 2
-- CREATE CONFORMED STORE DIMENSION
-- SCD TYPE 1 FOR STORE_MANAGER


CREATE OR REPLACE TABLE DIM_STORE (
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);


-- TASK 3
-- CREATE PRODUCT DIMENSION

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);



-- TASK 4
-- CREATE HYBRID CUSTOMER DIMENSION
--
-- Segment       = SCD TYPE 2
-- City          = SCD TYPE 3
-- Membership    = SCD TYPE 6

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),

    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),

    STATE VARCHAR(50),

    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),

    SEGMENT VARCHAR(30),

    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);



-- TASK 5
-- LOAD STORE DIMENSION FROM STAGING


INSERT INTO DIM_STORE (
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
)
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM STG_STORES;



-- LOAD PRODUCT DIMENSION FROM STAGING


INSERT INTO DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
FROM STG_PRODUCTS;



-- TASK 6
-- LOAD INITIAL CUSTOMER DIMENSION


INSERT INTO DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    NULL AS PREVIOUS_CITY,
    STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM STG_CUSTOMERS_INITIAL;


-- VERIFY INITIAL DIMENSIONS


SELECT *
FROM DIM_STORE
ORDER BY STORE_ID;


SELECT *
FROM DIM_PRODUCT
ORDER BY PRODUCT_ID;


SELECT *
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;




-- TASK 7
-- CREATE FACT SALES
--
-- GRAIN:
-- ONE ROW PER INDIVIDUAL ITEM LINE


CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,

    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,

    CUSTOMER_KEY NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,

    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(12,2),

    FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),

    FOREIGN KEY (STORE_KEY)
        REFERENCES DIM_STORE(STORE_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);



-- TASK 8
-- INSERT Q1 SALES



INSERT INTO FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1001',
    '2026-02-15'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    1 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 201
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 501
WHERE c.CUSTOMER_ID = 101
  AND c.IS_CURRENT = TRUE;


-- -----------
INSERT INTO FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1002',
    '2026-03-10'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    2,
    p.UNIT_PRICE,
    2 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 203
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 502
WHERE c.CUSTOMER_ID = 103
  AND c.IS_CURRENT = TRUE;


-- VERIFY Q1 FACT DATA

SELECT *
FROM FACT_SALES
ORDER BY TRANSACTION_DATE;




-- TASK 9
-- SCD TYPE 1
-- STORE MANAGER UPDATE


UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;


-- VERIFY

SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;




-- Verify only one row exists

SELECT
    STORE_ID,
    COUNT(*) AS RECORD_COUNT
FROM DIM_STORE
WHERE STORE_ID = 201
GROUP BY STORE_ID;




-- TASK 10
-- MULTI-ATTRIBUTE CUSTOMER UPDATES



-- STEP 1
-- EXPIRE CURRENT RECORDS


UPDATE DIM_CUSTOMER_HYBRID d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE;



-- STEP 2
-- INSERT NEW ACTIVE VERSIONS


INSERT INTO DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,

    -- New/current city
    u.CITY,

    -- Previous city from expired version
    old.CITY AS PREVIOUS_CITY,

    -- New/current state
    u.STATE,

    -- New/current membership
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,

    -- Previous membership
    old.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    -- Historical slice value
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    -- SCD2 segment
    u.SEGMENT,

    -- Effective date
    u.EFFECTIVE_DATE,

    -- Active record
    '9999-12-31'::DATE,

    TRUE

FROM STG_CUSTOMER_UPDATES u

JOIN DIM_CUSTOMER_HYBRID old
    ON old.CUSTOMER_ID = u.CUSTOMER_ID
   AND old.IS_CURRENT = FALSE
   AND old.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE);



-- STEP 3
-- SYNCHRONIZE CURRENT PROFILE ATTRIBUTES


UPDATE DIM_CUSTOMER_HYBRID d
SET
    CITY = c.CITY,
    STATE = c.STATE,
    CURRENT_MEMBERSHIP = c.CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = c.PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_HYBRID c
WHERE d.CUSTOMER_ID = c.CUSTOMER_ID
  AND c.IS_CURRENT = TRUE
  AND d.CUSTOMER_ID IN (
      SELECT CUSTOMER_ID
      FROM STG_CUSTOMER_UPDATES
  );



-- VERIFY CUSTOMER HISTORY


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;




-- TASK 11


INSERT INTO FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-2001',
    '2026-04-15'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    1 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 201
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 503
WHERE c.CUSTOMER_ID = 101
  AND c.IS_CURRENT = TRUE;



-- VERIFY ALL FACT SALES


SELECT
    f.SALES_KEY,
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    f.CUSTOMER_KEY,
    f.STORE_KEY,
    f.PRODUCT_KEY,
    f.QUANTITY,
    f.UNIT_PRICE,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
ORDER BY f.TRANSACTION_DATE;




-- TASK 12
-- DISPLAY COMPLETE CUSTOMER DIMENSION HISTORY


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;



-- TASK 13
-- POINT-IN-TIME POINT-OF-SALE ANALYTICS

SELECT
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,

    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,

    c.CITY AS CURRENT_CITY,

    c.HISTORICAL_MEMBERSHIP
        AS MEMBERSHIP_AT_PURCHASE,

    c.SEGMENT
        AS SEGMENT_AT_PURCHASE,

    s.STORE_NAME,

    p.PRODUCT_NAME,

    f.TOTAL_AMOUNT

FROM FACT_SALES f

JOIN DIM_CUSTOMER_HYBRID c
    ON f.CUSTOMER_KEY = c.CUSTOMER_KEY

JOIN DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY

JOIN DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY

WHERE c.CUSTOMER_ID = 101

ORDER BY f.TRANSACTION_DATE;





-- EXTRA: CHECK GRAIN


SELECT
    TRANSACTION_ID,
    PRODUCT_KEY,
    COUNT(*) AS LINE_COUNT
FROM FACT_SALES
GROUP BY
    TRANSACTION_ID,
    PRODUCT_KEY
ORDER BY
    TRANSACTION_ID;


-- Each transaction/product line should have one row.



-- TASK 14
-- WAREHOUSE RECORD COUNT AUDIT
-- SINGLE UNION ALL QUERY

SELECT
    'STORE DIMENSION RECORDS' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_STORE

UNION ALL

SELECT
    'PRODUCT DIMENSION RECORDS',
    COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'TOTAL CUSTOMER DIMENSION RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT
    'CURRENT CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'HISTORICAL CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE

UNION ALL

SELECT
    'FACT SALES TRANSACTIONS',
    COUNT(*)
FROM FACT_SALES;