USE WAREHOUSE MY_WH1;
USE DATABASE PRACTICE_DB;
USE SCHEMA TRAINING;

CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY INT AUTOINCREMENT PRIMARY KEY,
    PATIENT_ID VARCHAR(10),
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    CITY VARCHAR(50),
    STATE VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY INT AUTOINCREMENT PRIMARY KEY,
    DOCTOR_ID VARCHAR(10),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_HOSPITAL (
    HOSPITAL_KEY INT AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID VARCHAR(10),
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY INT AUTOINCREMENT PRIMARY KEY,
    DEPARTMENT_ID VARCHAR(10),
    DEPARTMENT_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_TREATMENT (
    TREATMENT_KEY INT AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID VARCHAR(10),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(50)
);

show tables;

CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY INT AUTOINCREMENT PRIMARY KEY,
    DOCTOR_ID VARCHAR(10),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_HOSPITAL (
    HOSPITAL_KEY INT AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID VARCHAR(10),
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY INT AUTOINCREMENT PRIMARY KEY,
    DEPARTMENT_ID VARCHAR(10),
    DEPARTMENT_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_TREATMENT (
    TREATMENT_KEY INT AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID VARCHAR(10),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(50)
);

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE HEALTHCARE_STAGE
FILE_FORMAT = CSV_FORMAT;

List @HEALTHCARE_STAGE

COPY INTO DIM_PATIENT
(PATIENT_ID, PATIENT_NAME, GENDER, CITY, STATE)
FROM @HEALTHCARE_STAGE/patients.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO DIM_DOCTOR
(DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION)
FROM @HEALTHCARE_STAGE/doctors.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO DIM_HOSPITAL
(HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, REGION)
FROM @HEALTHCARE_STAGE/hospitals.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO DIM_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME)
FROM @HEALTHCARE_STAGE/departments.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO DIM_TREATMENT
(TREATMENT_ID, TREATMENT_NAME, TREATMENT_CATEGORY)
FROM @HEALTHCARE_STAGE/treatments.csv
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INT PRIMARY KEY,
    FULL_DATE DATE,
    DAY INT,
    DAY_NAME VARCHAR(20),
    WEEK_NO INT,
    MONTH INT,
    MONTH_NAME VARCHAR(20),
    QUARTER VARCHAR(5),
    YEAR INT
);

INSERT INTO DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_KEY,
    DATE_VALUE AS FULL_DATE,
    DAY(DATE_VALUE) AS DAY,
    DAYNAME(DATE_VALUE) AS DAY_NAME,
    WEEKOFYEAR(DATE_VALUE) AS WEEK_NO,
    MONTH(DATE_VALUE) AS MONTH,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,
    'Q' || QUARTER(DATE_VALUE) AS QUARTER,
    YEAR(DATE_VALUE) AS YEAR
FROM (
    SELECT DATEADD(
        DAY,
        SEQ4(),
        '2026-01-01'::DATE
    ) AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 90))
);

CREATE OR REPLACE TABLE FACT_ADMISSION (
    ADMISSION_KEY INT AUTOINCREMENT PRIMARY KEY,
    PATIENT_KEY INT,
    DOCTOR_KEY INT,
    HOSPITAL_KEY INT,
    DEPARTMENT_KEY INT,
    DATE_KEY INT,
    ADMISSION_COUNT INT,
    LENGTH_OF_STAY INT
);

CREATE OR REPLACE TABLE FACT_BILLING (
    BILLING_KEY INT AUTOINCREMENT PRIMARY KEY,
    PATIENT_KEY INT,
    DOCTOR_KEY INT,
    HOSPITAL_KEY INT,
    DEPARTMENT_KEY INT,
    TREATMENT_KEY INT,
    DATE_KEY INT,
    QUANTITY INT,
    TREATMENT_AMOUNT NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    NET_AMOUNT NUMBER(10,2)
);

SELECT
    HOSPITAL_KEY,
    SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION
GROUP BY HOSPITAL_KEY
ORDER BY TOTAL_ADMISSIONS DESC;

SELECT
    H.HOSPITAL_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

SELECT
    H.HOSPITAL_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

SELECT COUNT(*) FROM FACT_BILLING;

-- Task 15 — Monthly Revenue

SELECT
    TO_CHAR(D.FULL_DATE, 'YYYY-MM') AS MONTH,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY TO_CHAR(D.FULL_DATE, 'YYYY-MM')
ORDER BY MONTH;


-- Task 16 — Doctor-wise Revenue.

SELECT
    D.DOCTOR_NAME,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_DOCTOR D
    ON F.DOCTOR_KEY = D.DOCTOR_KEY
GROUP BY D.DOCTOR_NAME
ORDER BY TOTAL_REVENUE DESC;

-- Task 17 — Drill-Across Analysis

SELECT
    H.HOSPITAL_NAME,
    COALESCE(A.TOTAL_ADMISSIONS, 0) AS TOTAL_ADMISSIONS,
    COALESCE(B.TOTAL_REVENUE, 0) AS TOTAL_REVENUE
FROM DIM_HOSPITAL H

LEFT JOIN (
    SELECT
        HOSPITAL_KEY,
        SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS
    FROM FACT_ADMISSION
    GROUP BY HOSPITAL_KEY
) A
    ON H.HOSPITAL_KEY = A.HOSPITAL_KEY

LEFT JOIN (
    SELECT
        HOSPITAL_KEY,
        SUM(NET_AMOUNT) AS TOTAL_REVENUE
    FROM FACT_BILLING
    GROUP BY HOSPITAL_KEY
) B
    ON H.HOSPITAL_KEY = B.HOSPITAL_KEY

ORDER BY TOTAL_ADMISSIONS DESC;