CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
WAREHOUSE_SIZE='X-SMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE RETAIL_WH;

CREATE OR REPLACE DATABASE RETAIL_DB;

USE DATABASE RETAIL_DB;

CREATE OR REPLACE SCHEMA SALES_SCHEMA;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE RETAIL_STAGE; 

CREATE OR REPLACE TABLE CUSTOMERS(
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(50),
CITY VARCHAR(10),
MEMBERSHIP VARCHAR(20)
);

CREATE OR REPLACE TABLE PRODUCTS
(
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE BRANCHES 
(
    BRANCH_ID INT,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(50)
);

CREATE OR REPLACE TABLE SALES
(
    SALE_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT);

COPY INTO PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT=(FORMAT_NAME = CSV_FILE_FORMAT);


COPY INTO BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT);


COPY INTO SALES 
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT=(FORMAT_NAME = CSV_FILE_FORMAT);

select * from customers;

SELECT COUNT(*) FROM CUSTOMERS;
SELECT COUNT(*) FROM PRODUCTS;
SELECT COUNT(*) FROM BRANCHES;
SELECT COUNT(*) FROM SALES

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC;

SELECT
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    P.CATEGORY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_SALES DESC;

SELECT
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 1;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 1;


SELECT
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 3;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 3;

SELECT
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT,
    RANK() OVER(
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

SELECT
    SALE_ID,
    CUSTOMER_ID,
    TOTAL_AMOUNT,
    ROW_NUMBER() OVER(
        ORDER BY TOTAL_AMOUNT DESC
    ) AS SALE_NUMBER
FROM SALES;

SELECT
    SALE_ID,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER() AS TOTAL_REVENUE
FROM SALES;

SELECT
    SALE_ID,
    TOTAL_AMOUNT,
    AVG(TOTAL_AMOUNT) OVER() AS AVERAGE_SALE
FROM SALES;

WITH customer_sales AS
(
    SELECT
        CUSTOMER_ID,
        SUM(TOTAL_AMOUNT) AS TOTAL_SPENT
    FROM SALES
    GROUP BY CUSTOMER_ID
)
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CS.TOTAL_SPENT
FROM customer_sales CS
JOIN CUSTOMERS C
    ON CS.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY CS.TOTAL_SPENT DESC;

CREATE OR REPLACE VIEW SALES_REPORT AS
SELECT
    S.SALE_ID,
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    B.BRANCH_NAME,
    S.QUANTITY,
    S.SALE_DATE,
    S.TOTAL_AMOUNT
FROM SALES S
JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN BRANCHES B
    ON S.BRANCH_ID = B.BRANCH_ID;

    SELECT *
FROM SALES_REPORT;

CREATE OR REPLACE MATERIALIZED VIEW TOP_CUSTOMERS AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME;

SELECT *
FROM TOP_CUSTOMERS
ORDER BY TOTAL_SPENT DESC
LIMIT 3;


