CREATE OR REPLACE WAREHOUSE STAR_SCHEMA_WH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME= TRUE; 

CREATE OR REPLACE DATABASE STAR_SCHEMA_DB;

CREATE OR REPLACE SCHEMA STAR_SCHEMA_DB.RETAIL_SCHEMA;

USE WAREHOUSE STAR_SCHEMA_WH;
USE DATABASE STAR_SCHEMA_DB;
USE SCHEMA RETAIL_SCHEMA;

CREATE OR REPLACE FILE FORMAT STAR_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE STAR_SCHEMA_STAGE
FILE_FORMAT = STAR_CSV_FORMAT;

LIST @STAR_SCHEMA_STAGE; 

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(20)
);

CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    BRAND VARCHAR(50),
    PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE DIM_BRANCH
(
    BRANCH_ID INT,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION VARCHAR(30),
    MANAGER_NAME VARCHAR(100)
);
CREATE OR REPLACE TABLE DIM_DATE
(
    DATE_ID INT,
    DATE DATE,
    DAY INT,
    DAY_NAME VARCHAR(20),
    WEEK_NO INT,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR INT,
    IS_WEEKEND VARCHAR(5)
);

CREATE OR REPLACE TABLE FACT_SALES
(
SALE_ID INT,
CUSTOMER_ID INT,
PRODUCT_ID INT,
BRANCH_ID INT,
DATE_ID  INT,
QUANTITY INT,
TOTAL_AMOUNT DECIMAL(12,2)

)

SHOW TABLES;

COPY INTO DIM_CUSTOMER
FROM @STAR_SCHEMA_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = STAR_CSV_FORMAT);

COPY INTO DIM_PRODUCT
FROM @STAR_SCHEMA_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = STAR_CSV_FORMAT); 

COPY INTO DIM_BRANCH
FROM @STAR_SCHEMA_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = STAR_CSV_FORMAT);

COPY INTO DIM_DATE
FROM @STAR_SCHEMA_STAGE/calendars.csv
FILE_FORMAT = (FORMAT_NAME = STAR_CSV_FORMAT);


COPY INTO FACT_SALES
FROM @STAR_SCHEMA_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = STAR_CSV_FORMAT);


-- REMOVE @STAR_SCHEMA_STAGE/customers.csv;
-- REMOVE @STAR_SCHEMA_STAGE/products.csv;
-- REMOVE @STAR_SCHEMA_STAGE/branches.csv;
-- REMOVE @STAR_SCHEMA_STAGE/calendars.csv;
-- REMOVE @STAR_SCHEMA_STAGE/sales.csv;

// JUST TO CHECK RELATION 
-- SELECT
--     F.SALE_ID,
--     C.CUSTOMER_NAME,
--     P.PRODUCT_NAME,
--     B.BRANCH_NAME,
--     D.DATE,
--     F.QUANTITY,
--     F.TOTAL_AMOUNT
-- FROM FACT_SALES F
-- JOIN DIM_CUSTOMER C
--     ON F.CUSTOMER_ID = C.CUSTOMER_ID
-- JOIN DIM_PRODUCT P
--     ON F.PRODUCT_ID = P.PRODUCT_ID
-- JOIN DIM_BRANCH B
--     ON F.BRANCH_ID = B.BRANCH_ID
-- JOIN DIM_DATE D
--     ON F.DATE_ID = D.DATE_ID
-- ORDER BY F.SALE_ID
-- LIMIT 10;

-- Customer-wise Sales Report
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

-- 1. Product-wise Revenue
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC

-- 2. Branch-wise Revenue

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

-- 3. State-wise Revenue
SELECT
    B.STATE,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.STATE
ORDER BY TOTAL_REVENUE DESC;
-- 4. Monthly Revenue
SELECT
    D.YEAR,
    D.MONTH,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.MONTH
ORDER BY
    D.YEAR,
    D.MONTH;

    -- 5. Quarterly Revenue

    SELECT
    D.YEAR,
    D.QUARTER,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.QUARTER
ORDER BY
    D.YEAR,
    D.QUARTER;

    -- 6. Top 10 Customers
    SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;
-- 7. Top 10 Products

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- 8. Top 10 Branches
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- 9. Category-wise Revenue
SELECT
    P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- 10. Customer Purchase Trends

-- This shows how frequently customers purchase and how much they spend.

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COUNT(F.SALE_ID) AS PURCHASE_COUNT,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC;

-- 11. Product Performance
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND
ORDER BY TOTAL_REVENUE DESC;

-- 12. Branch Performance
    SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    B.REGION,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    B.REGION
ORDER BY TOTAL_REVENUE DESC;

-- 13. Regional Sales
SELECT
    B.REGION,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.REGION
ORDER BY TOTAL_REVENUE DESC;

-- 14. Sales Trend

-- Daily sales over time:

SELECT
    D.DATE,
    SUM(F.TOTAL_AMOUNT) AS DAILY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.DATE
ORDER BY D.DATE;

-- 15. Overall Revenue

-- A useful final validation:

SELECT
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    COUNT(SALE_ID) AS TOTAL_SALES
FROM FACT_SALES;