USE WAREHOUSE STAR_SCHEMA_WH;

CREATE DATABASE IF NOT EXISTS CUSTOMER_HISTORY_DB;

CREATE SCHEMA IF NOT EXISTS CUSTOMER_HISTORY_DB.CUSTOMER_SCHEMA;

USE DATABASE CUSTOMER_HISTORY_DB;

USE SCHEMA CUSTOMER_SCHEMA;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY INT AUTOINCREMENT,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

LIST @CUSTOMER_STAGE;

COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_CSV_FORMAT);

SELECT *
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

-- REMOVE @CUSTOMER_STAGE/customers_initial.csv
-- REMOVE @CUSTOMER_STAGE/customer_updates.csv

COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_CSV_FORMAT);

SELECT *
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

-- changes of scd  and compare of data old vs new 

SELECT
    d.CUSTOMER_ID,
    d.CUSTOMER_NAME,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.STATE AS OLD_STATE,
    u.STATE AS NEW_STATE,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY
   OR d.STATE <> u.STATE
   OR d.MEMBERSHIP <> u.MEMBERSHIP
   OR d.SEGMENT <> u.SEGMENT
ORDER BY d.CUSTOMER_ID;

-- Task 7 — Identify Attribute Changes
SELECT
    d.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    d.CITY AS OLD_VALUE,
    u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    d.STATE AS OLD_VALUE,
    u.STATE AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.STATE <> u.STATE

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    d.MEMBERSHIP AS OLD_VALUE,
    u.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.MEMBERSHIP <> u.MEMBERSHIP

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    d.SEGMENT AS OLD_VALUE,
    u.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.SEGMENT <> u.SEGMENT

ORDER BY CUSTOMER_ID, ATTRIBUTE;

-- 1. Overwrite the changed customers

UPDATE DIM_CUSTOMER d
SET
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

SELECT *
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

-- Task 10 — Demonstrate Historical Data Loss

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;

-- Task 11 — Business Impact
Customer Dimension
       ↓
Attribute changes
       ↓
Normal UPDATE
       ↓
Old value replaced
       ↓
Historical information lost ❌