
--USE WAREHOUSE 
USE WAREHOUSE STAR_SCHEMA_WH;



CREATE OR REPLACE DATABASE PROJECT_11_DB;

USE DATABASE PROJECT_11_DB;

CREATE OR REPLACE SCHEMA HYBRID_SCD_SCHEMA;

USE SCHEMA HYBRID_SCD_SCHEMA;

CREATE OR REPLACE STAGE CUSTOMER_STAGE;

LIST @CUSTOMER_STAGE

--CSV FILE FORMAT
CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

COPY INTO STG_CUSTOMERS_INITIAL
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE
);

COPY INTO STG_CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- CREATE HYBRID DIMENSION


CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,

    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),

    CITY VARCHAR(100),
    PREVIOUS_CITY VARCHAR(100),

    STATE VARCHAR(100),

    CURRENT_MEMBERSHIP VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),

    SEGMENT VARCHAR(50),

    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,

    IS_CURRENT BOOLEAN
);
-- TASK 10 — LOAD INITIAL HYBRID DIMENSION

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,

    CITY,

    NULL AS PREVIOUS_CITY,

    STATE,

    MEMBERSHIP AS CURRENT_MEMBERSHIP,

    NULL AS PREVIOUS_MEMBERSHIP,

    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    SEGMENT,

    '2026-01-01'::DATE AS EFFECTIVE_DATE,

    '9999-12-31'::DATE AS EXPIRY_DATE,

    TRUE AS IS_CURRENT

FROM STG_CUSTOMERS_INITIAL;

-- TASK 11 — INITIAL DIMENSION STATE


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

-- TASK 12 — Apply Hybrid Updates
SELECT *
FROM STG_CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

-- TASK 12A — Expire Existing/Old Records

UPDATE DIM_CUSTOMER_HYBRID d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE;

--VERIFY 12A TASK
SELECT
    CUSTOMER_ID,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- TASK 12B — INSERT NEW ACTIVE VERSIONS


INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,

    u.CUSTOMER_NAME,

    -- New current city
    u.CITY,

    -- Previous city comes from the old version
    old.CITY AS PREVIOUS_CITY,

    -- State is overwritten
    u.STATE,

    -- New current membership
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,

    -- Old membership becomes previous membership
    old.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    -- Membership represented by this historical version
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    -- New segment
    u.SEGMENT,

    -- New version starts on update effective date
    u.EFFECTIVE_DATE,

    -- New version remains active
    '9999-12-31'::DATE AS EXPIRY_DATE,

    TRUE AS IS_CURRENT

FROM STG_CUSTOMER_UPDATES u

JOIN DIM_CUSTOMER_HYBRID old
    ON u.CUSTOMER_ID = old.CUSTOMER_ID

WHERE old.IS_CURRENT = FALSE
  AND old.EXPIRY_DATE =
      DATEADD(DAY, -1, u.EFFECTIVE_DATE);

-- TASK 12C — SYNCHRONIZE GLOBAL ATTRIBUTES
UPDATE DIM_CUSTOMER_HYBRID d
SET
    CITY = c.CITY,
    STATE = c.STATE,
    CURRENT_MEMBERSHIP = c.CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = c.PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_HYBRID c
WHERE d.CUSTOMER_ID = c.CUSTOMER_ID
  AND c.IS_CURRENT = TRUE;

  -- TASK 13 — COMPLETE HISTORY

  
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;

-- TASK 14 — ACTIVE CUSTOMER REPORT


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


-- TASK 15 — POINT-IN-TIME QUERY

SELECT

    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
  AND EFFECTIVE_DATE <= '2026-03-15'
  AND EXPIRY_DATE >= '2026-03-15';

-- TASK 16 — RECORD COUNT VALIDATION


SELECT
    COUNT(*) AS TOTAL_RECORD_COUNT,

    COUNT_IF(IS_CURRENT = TRUE)
        AS CURRENT_RECORD_COUNT,

    COUNT_IF(IS_CURRENT = FALSE)
        AS HISTORICAL_RECORD_COUNT

FROM DIM_CUSTOMER_HYBRID;