

--USE WAREHOUSE 
USE WAREHOUSE STAR_SCHEMA_WH;

-- TASK 1 — CREATE DATABASE AND SCHEMA


CREATE OR REPLACE DATABASE PROJECT_10_DB;

USE DATABASE PROJECT_10_DB;

CREATE OR REPLACE SCHEMA SCD_SCHEMA;

USE SCHEMA SCD_SCHEMA;



-- TASK 2 — CREATE TYPE 3 DIMENSION


CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD3 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    CURRENT_MEMBERSHIP VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);



-- TASK 3 — LOAD INITIAL TYPE 3 DATA


INSERT INTO DIM_CUSTOMER_SCD3
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
)
VALUES
(101, 'Amit Sharma', 'Hyderabad', 'Telangana', 'Silver', NULL, 'Regular'),
(102, 'Priya Reddy', 'Warangal', 'Telangana', 'Gold', NULL, 'Premium'),
(103, 'Rahul Verma', 'Vijayawada', 'Andhra Pradesh', 'Silver', NULL, 'Regular'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Gold', NULL, 'Premium'),
(105, 'Arjun Gupta', 'Nagpur', 'Maharashtra', 'Bronze', NULL, 'Regular');


-- VERIFY INITIAL LOAD

SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER_SCD3;





-- TASK 4 — DISPLAY INITIAL TYPE 3 DATA


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
ORDER BY CUSTOMER_ID;





-- TASK 5 + TASK 6
-- APPLY AND UPDATE SCD TYPE 3 CHANGES



UPDATE DIM_CUSTOMER_SCD3
SET
    PREVIOUS_MEMBERSHIP = CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP = 'Gold',
    CITY = 'Bengaluru',
    STATE = 'Karnataka',
    SEGMENT = 'Premium'
WHERE CUSTOMER_ID = 101;




UPDATE DIM_CUSTOMER_SCD3
SET
    PREVIOUS_MEMBERSHIP = CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP = 'Gold',
    CITY = 'Chennai',
    STATE = 'Tamil Nadu',
    SEGMENT = 'Premium'
WHERE CUSTOMER_ID = 103;



UPDATE DIM_CUSTOMER_SCD3
SET
    PREVIOUS_MEMBERSHIP = CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP = 'Platinum'
WHERE CUSTOMER_ID = 104;



-- TASK 7 — TYPE 3 FINAL REPORT


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
ORDER BY CUSTOMER_ID;






-- TASK 8 — DEMONSTRATE TYPE 3


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
WHERE CUSTOMER_ID = 101;




-- TASK 9 — CREATE TYPE 6 DIMENSION


CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD6 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    CURRENT_MEMBERSHIP VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);



-- TASK 10 — LOAD INITIAL TYPE 6 RECORDS


INSERT INTO DIM_CUSTOMER_SCD6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
VALUES
(
    101,
    'Amit Sharma',
    'Hyderabad',
    'Telangana',
    'Silver',
    NULL,
    'Silver',
    'Regular',
    '2026-01-01',
    '9999-12-31',
    TRUE
),
(
    102,
    'Priya Reddy',
    'Warangal',
    'Telangana',
    'Gold',
    NULL,
    'Gold',
    'Premium',
    '2026-01-01',
    '9999-12-31',
    TRUE
),
(
    103,
    'Rahul Verma',
    'Vijayawada',
    'Andhra Pradesh',
    'Silver',
    NULL,
    'Silver',
    'Regular',
    '2026-01-01',
    '9999-12-31',
    TRUE
),
(
    104,
    'Neha Patel',
    'Hyderabad',
    'Telangana',
    'Gold',
    NULL,
    'Gold',
    'Premium',
    '2026-01-01',
    '9999-12-31',
    TRUE
),
(
    105,
    'Arjun Gupta',
    'Nagpur',
    'Maharashtra',
    'Bronze',
    NULL,
    'Bronze',
    'Regular',
    '2026-01-01',
    '9999-12-31',
    TRUE
);


-- VERIFY INITIAL TYPE 6 LOAD

SELECT COUNT(*) AS TOTAL_RECORDS
FROM DIM_CUSTOMER_SCD6;


SELECT COUNT(*) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE;





-- TASK 11 — TYPE 6 CHANGE FOR CUSTOMER 101



-- STEP 1:
-- EXPIRE OLD CUSTOMER 101 RECORD

UPDATE DIM_CUSTOMER_SCD6
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;


-- STEP 2:
-- INSERT NEW CUSTOMER 101 VERSION

INSERT INTO DIM_CUSTOMER_SCD6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
VALUES
(
    101,
    'Amit Sharma',
    'Bengaluru',
    'Karnataka',
    'Gold',
    'Silver',
    'Gold',
    'Premium',
    '2026-04-01',
    '9999-12-31',
    TRUE
);


-- VERIFY CUSTOMER 101 HISTORY

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_SCD6
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;





-- TASK 12 — APPLY REMAINING TYPE 6 CHANGES



-- STEP 1: EXPIRE OLD RECORD

UPDATE DIM_CUSTOMER_SCD6
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;


-- STEP 2: INSERT NEW RECORD

INSERT INTO DIM_CUSTOMER_SCD6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
VALUES
(
    103,
    'Rahul Verma',
    'Chennai',
    'Tamil Nadu',
    'Gold',
    'Silver',
    'Gold',
    'Premium',
    '2026-04-05',
    '9999-12-31',
    TRUE
);


-- CUSTOMER 104
-- Gold -> Platinum

-- STEP 1: EXPIRE OLD RECORD

UPDATE DIM_CUSTOMER_SCD6
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;


-- STEP 2: INSERT NEW RECORD

INSERT INTO DIM_CUSTOMER_SCD6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
VALUES
(
    104,
    'Neha Patel',
    'Hyderabad',
    'Telangana',
    'Platinum',
    'Gold',
    'Platinum',
    'Premium',
    '2026-04-10',
    '9999-12-31',
    TRUE
);



-- TASK 13 — DISPLAY COMPLETE TYPE 6 HISTORY


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_SCD6
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;



-- TASK 14 — CURRENT CUSTOMER REPORT


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;




-- TASK 15 — POINT-IN-TIME HISTORICAL QUERY


-- QUESTION:
-- What was Customer 101's membership on March 15, 2026?

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_SCD6
WHERE CUSTOMER_ID = 101
  AND EFFECTIVE_DATE <= '2026-03-15'
  AND EXPIRY_DATE >= '2026-03-15';






-- TASK 16 — TYPE 3 VS TYPE 6 COMPARISON


-- SCD TYPE 3
--
-- Current Value       YES
-- Previous Value      YES
-- Historical Rows     NO
-- Effective Date      NO
-- Expiry Date         NO
-- IS_CURRENT          NO
--
--
-- SCD TYPE 6
--
-- Current Value       YES
-- Previous Value      YES
-- Historical Rows     YES
-- Effective Date      YES
-- Expiry Date         YES
-- IS_CURRENT          YES


-- TASK 17 — RECORD COUNT VALIDATION



-- TYPE 3 RECORD COUNT

SELECT
    COUNT(*) AS SCD_TYPE_3_RECORD_COUNT
FROM DIM_CUSTOMER_SCD3;




-- TYPE 6 TOTAL RECORD COUNT

SELECT
    COUNT(*) AS SCD_TYPE_6_RECORD_COUNT
FROM DIM_CUSTOMER_SCD6;





-- TYPE 6 CURRENT RECORD COUNT

SELECT
    COUNT(*) AS SCD_TYPE_6_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE;




-- TYPE 6 HISTORICAL RECORD COUNT

SELECT
    COUNT(*) AS SCD_TYPE_6_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = FALSE;





-- FINAL VALIDATION


SELECT
    (SELECT COUNT(*) FROM DIM_CUSTOMER_SCD3)
        AS SCD_TYPE_3_RECORD_COUNT,

    (SELECT COUNT(*) FROM DIM_CUSTOMER_SCD6)
        AS SCD_TYPE_6_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_SCD6
     WHERE IS_CURRENT = TRUE)
        AS SCD_TYPE_6_CURRENT_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_SCD6
     WHERE IS_CURRENT = FALSE)
        AS SCD_TYPE_6_HISTORICAL_RECORD_COUNT;